# .gitpod.yml
tasks:
  - name: Set up VNC & Raylib
    init: |
      # Install VNC, XFCE (lightweight desktop), and Raylib dependencies
      sudo apt-get update
      sudo apt-get install -y tigervnc-standalone-server xfce4 xfce4-goodies libgl1-mesa-dev xorg-dev git make g++

      # Set up VNC password (default: "123456")
      mkdir -p ~/.vnc
      echo "123456" | vncpasswd -f > ~/.vnc/passwd
      chmod 600 ~/.vnc/passwd

      # Clone and compile Raylib
      git clone --depth 1 https://github.com/raysan5/raylib.git
      cd raylib/src
      make PLATFORM=PLATFORM_DESKTOP
      sudo make install
      cd ../..